# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-29 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36, verbose_name='书名')),
                ('price', models.PositiveIntegerField(max_length=10, verbose_name='价格')),
                ('publish', models.CharField(max_length=30, verbose_name='出版社')),
            ],
        ),
    ]
