# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-29 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190429_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(verbose_name='价格'),
        ),
    ]
